# Generated by Django 6.0.4 on 2026-04-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'calendar_room',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('empty', 'Empty'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], max_length=16)),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bigCalendar.room')),
            ],
            options={
                'db_table': 'calendar_event',
                'indexes': [models.Index(fields=['room', 'event_start', 'event_end'], name='calendar_ev_room_id_2fdca7_idx'), models.Index(fields=['updated_at'], name='calendar_ev_updated_a4715a_idx')],
            },
        ),
    ]
